// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2bJuxwhwI5u9u2t6nPx4GeV6JFsMJiQU',
    appId: '1:435691774326:web:00cc8e8ad1b6d37af71a57',
    messagingSenderId: '435691774326',
    projectId: 'erp-apps-6396f',
    authDomain: 'erp-apps-6396f.firebaseapp.com',
    storageBucket: 'erp-apps-6396f.firebasestorage.app',
    measurementId: 'G-YTG9G8G41R',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBS5Xvhp17dS7xwwKvN6K9hXUTRiudutqo',
    appId: '1:435691774326:ios:7b9b27e9a6755ec2f71a57',
    messagingSenderId: '435691774326',
    projectId: 'erp-apps-6396f',
    storageBucket: 'erp-apps-6396f.firebasestorage.app',
    iosBundleId: 'com.example.erpApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBS5Xvhp17dS7xwwKvN6K9hXUTRiudutqo',
    appId: '1:435691774326:ios:7b9b27e9a6755ec2f71a57',
    messagingSenderId: '435691774326',
    projectId: 'erp-apps-6396f',
    storageBucket: 'erp-apps-6396f.firebasestorage.app',
    iosBundleId: 'com.example.erpApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2bJuxwhwI5u9u2t6nPx4GeV6JFsMJiQU',
    appId: '1:435691774326:web:8124a042ec95657ef71a57',
    messagingSenderId: '435691774326',
    projectId: 'erp-apps-6396f',
    authDomain: 'erp-apps-6396f.firebaseapp.com',
    storageBucket: 'erp-apps-6396f.firebasestorage.app',
    measurementId: 'G-YNCGCSYKVQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANxYQtqMfArqy-oxQdT90R-UKDxhSGUK0',
    appId: '1:435691774326:android:c965098adc0a01eff71a57',
    messagingSenderId: '435691774326',
    projectId: 'erp-apps-6396f',
    storageBucket: 'erp-apps-6396f.firebasestorage.app',
  );

}